geladeirinha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('api/', include('tarefas.urls', namespace='api'))

]

tarefas/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'tarefas'

urlpatterns = [
    path('<int:pk>/', DetailTodo.as_view(),name='detalhe'),
    path('', ListTodo.as_view(), name='list-todo'),
    path('create/', CreateTodo.as_view(), name='create_todo'),
    path('delete/<int:pk>', DeleteTodo.as_view(), name='delete-todo'),
    path('options/', options, name='options-html'),
    path('confirm-delete/<int:pk>', ConfirmDeleteTodo.as_view() , name= 'confirm-delete')
]

usuarios/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.logar, name='login'),
    path('logout/', views.logout, name='logout'),
    path('plataforma/', views.plataforma, name='plataforma'),
    path('social/', include('allauth.socialaccount.urls')),
    path('', views.landing_page, name = 'landing_page')
    
]

tarefas/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    Title = models.CharField(max_length=100, blank=False)
    Description = models.TextField(blank=True)
    Date = models.DateField(blank=False)
    Completed = models.BooleanField(default=False)
def __str__(self):
        return self.Title

usuarios/models.py
from django.db import models

# Create your models here.

tarefas/views.py
from django.shortcuts import render, redirect,get_object_or_404
from rest_framework import generics, status
from .serializers import *
from .models import *
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from django.contrib import messages
from rest_framework.views import APIView
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class ListTodo(generics.ListAPIView):
    queryset = Todo.objects.all()
    serializer_class = ToDoSerializer
    template_name = 'todo_list.html'
    
    def get(self, request, *args, **kwargs):
        todos = Todo.objects.all()
        contexto = {
            'caminho_para_bootstrap_css': 'https://bootswatch.com/morph/bootstrap.min.css',
            'todos' : todos,
        }
        return render(request, self.template_name, contexto)

class DetailTodo(generics.RetrieveUpdateAPIView):
    queryset = Todo.objects.all()
    serializer_class = ToDoSerializer


class CreateTodo(generics.CreateAPIView):
    queryset = Todo.objects.all()
    serializer_class = ToDoSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "create.html"

    def get(self, request):
        serializer = self.serializer_class()
        return render(request, self.template_name, {'serializer': serializer})
   
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('tarefas:options-html')
        else:
            return render(request, self.template_name, {'serializer': serializer})

class DeleteTodo(View):
    def post(self, request, pk):
        todo = get_object_or_404(Todo, pk=pk)
        todo.delete()
        return redirect('tarefas:list-todo')


class ConfirmDeleteTodo(View):
    template_name = 'confirm_delete.html'

    def get(self, request, pk):
        todo = get_object_or_404(Todo, pk=pk)
        context = {
            'todo': todo,
        }
        return render(request, self.template_name, context)

def options(request):
    return render(request, 'options.html')

usuarios/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def cadastro(request):
    if request.method == 'GET':
        return render(request, 'cadastro.html')
    else:
        username= request.POST.get('username')
        email= request.POST.get('email')
        senha= request.POST.get('senha')
        
    user = User.objects.filter(username=username).first()
    
    if user:
        return HttpResponse('USUÁRIO JA CADASTRADO')
    
    user = User.objects.create_user(username=username, email=email, password=senha)
    user.save()
    return HttpResponse("USUARIO CADASTRADO COM SUCESSO!")

def logar(request):
    if request.method == "GET":
        return render(request, 'gelalogin.html')
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(username=username, password=senha)
        
        if user:
            login(request,user)
            return redirect(reverse('api:tarefas:create_todo'))
        else:
            return HttpResponse('EMAIL OU SENHA INVÁLIDOS!')

def my_logout(request):
    logout(request)
    return HttpResponse('Logout Realizado.')
        

def plataforma(request):
        return render(request, 'logado.html',{'user':request.user})

def landing_page(request):
    return render(request, 'geladeirinha.html')


# Create your views here.

tarefas/templates/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmação de Exclusão</title>
</head>
<body>
    <h1>Confirmação de Exclusão</h1>
    <p>Tem certeza que deseja excluir esta tarefa?</p>
    <form action="{% url 'tarefas:delete-todo' pk=todo.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="confirmed" value="true">
        <button type="submit" class="btn btn-danger">Sim, excluir</button>
        <a href="{% url 'tarefas:list-todo' %}" class="btn btn-primary">Cancelar</a>
    </form>
</body>
</html>

tarefas/templates/create.html
{% load rest_framework %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Criar uma Tarefa</title>
</head>
<body>
    <h1 class="text-center">Criar uma Tarefa</h1>
    {% if success_message %}
    <p class="text-success">{{ success_message }}</p>
    {% endif %}
<form action="{% url 'tarefas:create_todo' %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %} 
    <input type="submit" value="Save">
</form>
</body>
</html>

tarefas/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmação de Exclusão</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
</head>
<body>
    <h1 class="text-body-secondary">Confirmação de Exclusão</h1>
    <p class="text-body-secondary">Deseja excluir a tarefa: {{ todo.Title }}?</p>
    
    <form class="delete-form" action="{% url 'tarefas:delete-todo' pk=todo.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Sim, Excluir</button>
    </form>
    
    <a href="{% url 'tarefas:list-todo' %}" class="btn btn-secondary">Cancelar</a>
</body>
</html>

tarefas/templates/options.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Geladeirinha</title>
</head>
<body class="container">
    <div class="header">
        <h1>Boa! A sua tarefa foi gravada</h1>
        <a href="{% url 'tarefas:list-todo' %}" class="btn btn-primary">Ver Lista de Tarefas</a>
        <a href="{% url 'tarefas:create_todo' %}" class="btn btn-secondary">Registrar Outra Tarefa</a>
        
    </div>
    
</body>
</html>

tarefas/templates/todo_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de tarefas</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
</head>
<body>
    <h1 class="text-body-secondary">Lista de Tarefas</h1>
    <ul>
        {% for todo in todos %}
        <li>
            {{ todo.Title }}, {{ todo.Completed }}, {{ todo.Description }}, {{ todo.Date }},
            <a href="{% url 'tarefas:confirm-delete' pk=todo.id %}" class="btn btn-danger">Excluir</a>
        </li>
        {% endfor %}
    </ul>

usuarios/templates/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style/styles.css' %}">
    <title>CADASTRO GELADEIRINHA</title>
</head>
<body class="container">
    <div class="header">
        <form action="{% url 'cadastro'%}" method="POST">{% csrf_token %}
            <img class="img" src="{% static 'images/geladeirinha-logo.png' %}" alt="Geladeirinha">
            <h1>CADASTRO GELADEIRINHA</h1>
            <div class=" inputs">
                <input class="input-field" type="text" placeholder="USERNAME..." name="username">
                <input class="input-field" type="email" placeholder="EMAIL..." name="email">
                <input class="input-field" type="password" placeholder="SENHA..." name="senha">
                <input class="button" type="submit" value="CADASTRAR">
            </div>
        </form>
    </div>


</body>
</html>

usuarios/templates/geladeirinha.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/geladeirinhacss.css' %}">
</head>
<body>
    <div style="width: 100%; height: 100%; position: relative; background: white">
        <div style="width: 94px; height: 94px; left: 36px; top: 36px; position: absolute">
            <svg width="94" height="94" viewBox="0 0 94 94" fill="none" xmlns="http://www.w3.org/2000/svg">
                <mask id="mask0_99_327" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="94" height="94">
                <rect width="94" height="94" rx="15" fill="#EFE1D7"/>
                </mask>
                <g mask="url(#mask0_99_327)">
                <path d="M35.7213 54.52C35.7213 57.5117 36.9097 60.3808 39.0251 62.4962C41.1405 64.6116 44.0096 65.8 47.0013 65.8C49.9929 65.8 52.862 64.6116 54.9774 62.4962C57.0928 60.3808 58.2812 57.5117 58.2812 54.52L47.0013 54.52L35.7213 54.52Z" fill="#313131"/>
                <path d="M50.7598 58.28L50.7598 62.04C50.7598 64.1166 49.0764 65.8 46.9998 65.8V65.8C44.9232 65.8 43.2398 64.1166 43.2398 62.04L43.2398 58.28L50.7598 58.28Z" fill="#FF5454"/>
                <circle cx="23.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="23.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="70.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="25.3797" cy="44.18" r="4.7" fill="#FBF1F1"/>
                <circle cx="72.3797" cy="44.18" r="4.7" fill="#FBF1F1"/>
                </g>
                </svg>
                
        </div>
        <div style="left: 154px; top: 75px; position: absolute; color: black; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Geladeirinha</div>
        <div style="left: 290px; top: 260px; position: absolute; color: black; font-size: 64px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Sua rotina.<br/>Mais produtiva e<br/>organizada.</div>
        <div style="left: 290px; top: 1225px; position: absolute; color: black; font-size: 64px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Clientes satisfeitos.<br/>E cada vez mais deles<br/>por aqui.</div>
        <div style="left: 290px; top: 2345px; position: absolute; color: black; font-size: 64px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Use o que precisar.<br/>Sem salvar coisas <br/>em outras coisas.</div>
        <div style="left: 290px; top: 5045px; position: absolute; color: black; font-size: 64px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Seu espaço.<br/>Interagindo com<br/>todas as áreas.</div>
        <div style="width: 380px; height: 53px; left: 290px; top: 668px; position: absolute; background: black; border-radius: 8px"></div>
        <div style="width: 380px; height: 53px; left: 290px; top: 1633px; position: absolute; background: black; border-radius: 8px"></div>
        <div style="left: 316px; top: 684px; position: absolute; color: #E6E6E6; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word"><a href="/login" style="text-decoration: none; color: #E6E6E6;"> Comece a usar o Geladeirinha</a></div>
        <div style="left: 352px; top: 1649px; position: absolute; color: #E6E6E6; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word"><a href="/login" style="text-decoration: none; color: #E6E6E6;">Veja nossas avaliações</a></div>
        <div style="left: 290px; top: 534px; position: absolute; color: black; font-size: 32px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Geladeirinha é onde toda a sua rotina se torna mais<br/>leve e confortável, não importa o seu ambiente.</div>
        <div style="left: 290px; top: 1499px; position: absolute; color: black; font-size: 32px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Geladeirinha encanta todos quando se trata em mostrar<br/>uma nova experiência de organização.</div>
        <div style="left: 317px; top: 75px; position: absolute; color: black; font-size: 20px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Produtos</div>
        <div style="left: 423px; top: 75px; position: absolute; color: black; font-size: 20px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Soluções</div>
        <div style="left: 531px; top: 75px; position: absolute; color: black; font-size: 20px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Recursos</div>
        <div style="width: 246px; height: 53px; left: 1043px; top: 60px; position: absolute; background: black; border-radius: 8px"></div>
<div style="left: 1074px; top: 75px; position: absolute; color: #E6E6E6; font-size: 20px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Utilize gratuitamente</div>
<div style="left: 1321px; top: 75px; position: absolute; color: black; font-size: 20px; font-family: Archivo; font-weight: 400; word-wrap: break-word"><a href="/login" style="text-decoration: none; color: #000000;">Entrar</a></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 2688px; position: absolute; background: #EEFFBD; box-shadow: 50px 50px 50px; filter: blur(50px)"></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 2688px; position: absolute; background: rgba(244.37, 244.37, 244.37, 0.95)"></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 3539px; position: absolute; background: #CEBDFF; box-shadow: 50px 50px 50px; filter: blur(50px)"></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 3539px; position: absolute; background: rgba(244.37, 244.37, 244.37, 0.95)"></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 4438px; position: absolute; background: #BDFFCC; box-shadow: 50px 50px 50px; filter: blur(50px)"></div>
        <div style="width: 774px; height: 435px; left: 290px; top: 4438px; position: absolute; background: rgba(244.37, 244.37, 244.37, 0.95)"></div>
        <div style="width: 906px; height: 435px; left: 290px; top: 5562px; position: absolute; background: rgba(244.37, 244.37, 244.37, 0.95)"></div>
        <div style="width: 150px; height: 150px; left: 286px; top: 5345px; position: absolute; background: #D9D9D9"></div>
        <div style="width: 150px; height: 150px; left: 476px; top: 5345px; position: absolute; background: #D9D9D9"></div>
        <div style="width: 150px; height: 150px; left: 666px; top: 5345px; position: absolute; background: #D9D9D9"></div>
        <div style="width: 150px; height: 150px; left: 856px; top: 5345px; position: absolute; background: #D9D9D9"></div>
        <div style="width: 150px; height: 150px; left: 1046px; top: 5345px; position: absolute; background: #D9D9D9"></div>
        <div style="left: 290px; top: 6213px; position: absolute; color: black; font-size: 64px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Comece agora.<br/>Sem custos e com o<br/>Geladeirinha por perto.</div>
        <div style="width: 380px; height: 53px; left: 290px; top: 6621px; position: absolute; background: black; border-radius: 8px"></div>
        <div style="left: 316px; top: 6637px; position: absolute; color: #E6E6E6; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word"><a href="/cadastro" style="text-decoration: none; color: #E6E6E6;">Comece a usar o Geladeirinha</a></div>
        <div style="left: 290px; top: 6487px; position: absolute; color: black; font-size: 32px; font-family: Archivo; font-weight: 400; word-wrap: break-word">Teste, de graça, o Geladeirinha. Adicione toda sua estrutura<br/>por um preço depois.</div>
        <div style="width: 1440px; height: 821px; left: 0px; top: 7047px; position: absolute; background: #313131"></div>
        <div style="width: 100px; height: 100px; left: 290px; top: 7118px; position: absolute; background: #D9D9D9; border-radius: 24px"></div>
        <div style="left: 427px; top: 7157px; position: absolute; color: white; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Geladeirinha</div>
        <div style="left: 638px; top: 7157px; position: absolute; color: white; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Produtos</div>
        <div style="left: 638px; top: 7207px; position: absolute; color: white; font-size: 20px; font-family: Archivo; font-weight: 400; line-height: 32px; word-wrap: break-word">Produto<br/>Produto<br/>Produto</div>
        <div style="left: 809px; top: 7207px; position: absolute; color: white; font-size: 20px; font-family: Archivo; font-weight: 400; line-height: 32px; word-wrap: break-word">Solução<br/>Solução<br/>Solução</div>
        <div style="left: 982px; top: 7207px; position: absolute; color: white; font-size: 20px; font-family: Archivo; font-weight: 400; line-height: 32px; word-wrap: break-word">Recurso<br/>Recurso<br/>Recurso</div>
        <div style="left: 638px; top: 7409px; position: absolute; color: white; font-size: 20px; font-family: Archivo; font-weight: 400; line-height: 32px; word-wrap: break-word">O que somos<br/>Trabalhe conosco<br/>Contate-nos</div>
        <div style="left: 809px; top: 7157px; position: absolute; color: white; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Soluções</div>
        <div style="left: 982px; top: 7157px; position: absolute; color: white; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Recursos</div>
        <div style="left: 638px; top: 7359px; position: absolute; color: white; font-size: 20px; font-family: Archivo Black; font-weight: 400; word-wrap: break-word">Sobre Nós</div>
        <div style="width: 94px; height: 94px; left: 293px; top: 7121px; position: absolute">
            <svg width="94" height="94" viewBox="0 0 94 94" fill="none" xmlns="http://www.w3.org/2000/svg">
                <mask id="mask0_99_327" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="94" height="94">
                <rect width="94" height="94" rx="15" fill="#EFE1D7"/>
                </mask>
                <g mask="url(#mask0_99_327)">
                <path d="M35.7213 54.52C35.7213 57.5117 36.9097 60.3808 39.0251 62.4962C41.1405 64.6116 44.0096 65.8 47.0013 65.8C49.9929 65.8 52.862 64.6116 54.9774 62.4962C57.0928 60.3808 58.2812 57.5117 58.2812 54.52L47.0013 54.52L35.7213 54.52Z" fill="#313131"/>
                <path d="M50.7598 58.28L50.7598 62.04C50.7598 64.1166 49.0764 65.8 46.9998 65.8V65.8C44.9232 65.8 43.2398 64.1166 43.2398 62.04L43.2398 58.28L50.7598 58.28Z" fill="#FF5454"/>
                <circle cx="23.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="23.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="70.4996" cy="46.06" r="9.4" fill="#4A4A4A"/>
                <circle cx="25.3797" cy="44.18" r="4.7" fill="#FBF1F1"/>
                <circle cx="72.3797" cy="44.18" r="4.7" fill="#FBF1F1"/>
                </g>
                </svg>
                
        </div>
    </div>
</body>
</html>

usuarios/templates/logado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página após login</title>
</head>
<body>
    <h1>Usuário logado: {{ user.username }}</h1>
    <a href="{% url 'logout' %}">Sair</a>
</body>
</html>

usuarios/templates/login.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="geladeirinha icon" type="png" href="{% static 'images/geladeirinha-logo.png' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style/styles.css' %}">
    <title>LOGIN GELADEIRINHA</title>
</head>
<body class="container">
    <div class="header" id="login">
        <form class="login-form" action="{% url 'login'%}" method="POST">
            <img class="img" src="{% static 'images/geladeirinha-logo.png' %}" alt="Geladeirinha">
            <h1>LOGIN GELADEIRINHA</h1>
            <div class="inputs">
                {% csrf_token %}
                <input class="input-field" type="text" placeholder="USERNAME..." name="username">
                <input class="input-field" type="password" placeholder="SENHA..." name="senha">
                <input class="button" type="submit" value="LOGAR">
            </div>
        </form>
    </div>

</body>
</html>